### Default ###
spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 32MB
jasypt:
  encryptor:
    property:
      prefix: ENC(
      suffix: )
    algorithm: PBEWithMD5AndDES
custom:
  jwt:
    secret: ENC(8XTUwqaABXWvQy95s5btt3I84RATF9db8QBlXRWDv/AManI8wvJZo9s4Uj/wRS/+qAHfp3RarJCNB02/v2yWiT8/c6+/G8lRLwtMxY2/+ukAXc+KPhVIeA==)
cloud:
  aws:
    credentials:
      accessKey: ENC(1Mc71aJBUmefjs+ku/HVcGVKXIA3tK/nCujVlugXfB0=)
      secretKey: ENC(cSNVjbLMKfqHgV/+2bdzkCTaPoETDyi4Frx7S4HXqEwMdtScIcHRvkvWjRgxPuSl1381FcWvjbU=)
    s3:
      bucket: ENC(A7aOZ7NaUedXlRPFDHJUr+u9YC7iFdzF)
    region:
      static: ENC(8/e0Kt6GTaAqr/FFWWUZqN/8RIcGBs7E)
server:
  port: 8080

---

### Local Environment ###
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: create

---

## Deployment Environment ###
spring:
  config:
    activate:
      on-profile: deploy
  datasource:
    url: ENC(WvuKok77iSC1MpLuPOiy4GP0pIBhoofSXSmFiIkqdpbuWB0tWO/Hipcf92PpADHJYDrobjGo51E0ulxxF6tQ1m+J1cM/VxiT8FLttE++LvP4wEbPOb0E7TaHcfm7wbQPZTTbhfX5TJbS1vxeSHQy0kCKKHwhaBAcTfAoix3Du9v+AvnoEUK1pFoQLneyV/ALKRYIWccngpM=)
    driver-class-name: org.mariadb.jdbc.Driver
    username: ENC(Ur6nyAvFUR3XBrLKcun5LQ==)
    password: ENC(06cigUOMu92LmoVZp5hBlVNPOeL5TyAC)
